<?php $title = 'Mentions légales'; ?>
<?php ob_start() ?>
  <div class="container text-light mb-4 ">
    <h2 class="text-center mt-5 mb-5">MENTIONS LEGALES :</h2>
    <p class="text-justify">Conformément aux dispositions des articles 6-III et 19 de la Loi n° 2004-575 du 21 juin 2004 pour la Confiance dans l'économie numérique, dite L.C.E.N., nous portons à la connaissance des utilisateurs et visiteurs du site : www.agence-de-tourisme-strasbourg.webagency-sonny.fr les informations suivantes :</p>
    <p class="text-justify"><strong>1. Informations légales :</strong></p>
    <p class="text-justify">Statut du propriétaire : <strong>particulier</strong><br>Le Propriétaire est : <strong>Erickson Sonny</strong><br>Adresse postale du propriétaire : <strong>17 place de la Cathédrale 67082 Strasbourg</strong></p>
    <p>Le Créateur du site est : <strong>agence-de-tourisme-strasbourg.webagency-sonny.fr</strong><br>Le Responsable de la&nbsp; publication est : <strong>sonny erickson</strong><br>Contacter le responsable de la publication : <strong>abc@hotmail.fr</strong><br>Le responsable de la publication est une<strong>&nbsp;personne physique</strong></p>
    <p>Le Webmaster est&nbsp; : <strong>Sonny erickson</strong><br>Contacter le Webmaster :&nbsp; <strong>abc@hotmail.fr</strong><br>L’hebergeur du site est : <strong>1and1 Rue ionos 63110 beaumont</strong><br><strong><u>CREDIT :</u> </strong>&nbsp;Les mentions légales ont étés générées par<strong>&nbsp;<a href="https://www.generer-mentions-legales.com/generateur-mentions-legales.html" target="_blank" rel="noopener noreferrer">générateur de mentions legales</a></strong><br>Une eau toujours potable avec les&nbsp;<strong><a href="https://www.chamarrel.com/perles-de-ceramique-em-pxl-29_37.html">perles de céramique</a></strong></p>
    <p class="text-justify">&nbsp;</p>
    <p class="text-justify"><strong>2. Présentation et principe :</strong></p>
    <p class="text-justify">Est désigné ci-après : <strong>Utilisateur</strong>, tout internaute se connectant et utilisant le site susnommé : www.GG.fr.<br>Le site <strong>www.GG.fr</strong> regroupe un ensemble de services, dans l'état,&nbsp; mis à la disposition des utilisateurs. Il est ici précisé que ces derniers doivent rester courtois et faire preuve de bonne foi tant envers les autres utilisateurs qu'envers le webmaster du site www.GG.fr. Le site www.GG.fr est mis à jour régulièrement par Sonny erickson.<br>Erickson Sonny s’efforce de fournir sur le site www.GG.fr des informations les plus précises possibles (sous réserve de modifications apportées depuis leur mise en ligne), mais ne saurait garantir l'exactitude, la complétude et l'actualité des informations diffusées sur son site, qu’elles soient de son fait ou du fait des tiers partenaires qui lui fournissent ces informations. En conséquence, l'utilisateur reconnaît utiliser ces informations données (à titre indicatif, non exhaustives et susceptibles d'évoluer) sous sa responsabilité exclusive.</p>
    <p class="text-justify">&nbsp;</p>
    <p class="text-justify"><strong>3. Accessibilité :</strong></p>
    <p>Le site www.GG.fr est par principe accessible aux utilisateurs 24/24h, 7/7j, sauf interruption, programmée ou non, pour les besoins de sa maintenance ou en cas de force majeure. En cas d’impossibilité d’accès au service, www.GG.fr s’engage à faire son maximum afin de rétablir l’accès au service et s’efforcera alors de communiquer préalablement aux utilisateurs les dates et heures de l’intervention.&nbsp; N’étant soumis qu’à une obligation de moyen, www.GG.fr ne saurait être tenu pour responsable de tout dommage, quelle qu’en soit la nature, résultant d’une indisponibilité du service.</p>
    <p class="text-justify">&nbsp;</p>
    <p class="text-justify"><strong>4. Propriété intellectuelle :</strong></p>
    <p class="text-justify">GG est propriétaire exclusif de tous les droits de propriété intellectuelle ou détient les droits d’usage sur tous les éléments accessibles sur le site, tant sur la structure que sur les textes, images, graphismes, logo, icônes, sons, logiciels…<br>Toute reproduction totale ou partielle du site www.GG.fr, représentation, modification, publication, adaptation totale ou partielle de l'un quelconque de ces éléments, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de Erickson Sonny, propriétaire du site à l'email : abc@hotmail.fr, à défaut elle sera considérée comme constitutive d’une contrefaçon et passible de poursuite conformément aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle.</p>
    <p class="text-justify"><strong>5. Liens hypertextes et cookies :</strong></p>
    <p>Le site www.GG.fr contient un certain nombre de liens hypertextes vers d’autres sites (partenaires, informations …) mis en place avec l’autorisation de Erickson Sonny. Cependant, Erickson Sonny n’a pas la possibilité de vérifier l'ensemble du contenu des sites ainsi visités&nbsp;et décline donc toute responsabilité de ce fait quand aux risques éventuels de contenus illicites.<br>L’utilisateur est informé que lors de ses visites sur le site www.GG.fr, un ou des cookies sont susceptibles de s’installer automatiquement sur son ordinateur par l'intermédiaire de son logiciel de navigation. Un cookie est un bloc de données qui ne permet pas d'identifier l'utilisateur, mais qui enregistre des informations relatives à la navigation de celui-ci sur le site.<br>Le paramétrage du logiciel de navigation permet d’informer de la présence de cookie et éventuellement, de la refuser de la manière décrite à l’adresse suivante : <a href="http://www.cnil.fr">www.cnil.fr</a>. L’utilisateur peut toutefois configurer le navigateur de son ordinateur pour refuser l’installation des cookies, sachant que le refus d'installation d'un cookie peut entraîner l’impossibilité d’accéder à certains services. Pour tout bloquage des cookies, tapez dans votre moteur de recherche : bloquage des cookies sous IE ou firefox et suivez les instructions en fonction de votre version.</p>
    <p class="text-justify"><strong>6. Protection des biens et des personnes - gestion des données personnelles :</strong></p>
    <p>En France, les données personnelles sont notamment protégées par la loi n° 78-87 du 6 janvier 1978, la loi n° 2004-801 du 6 août 2004, l'article L. 226-13 du Code pénal et la Directive Européenne du 24 octobre 1995.</p>
    <p class="text-justify">Sur le site www.GG.fr, Erickson Sonny ne collecte des informations personnelles ( suivant l'article 4 loi n°78-17 du 06 janvier 1978) relatives à l'utilisateur que pour le besoin de certains services proposés par le site www.GG.fr. L'utilisateur fournit ces informations en toute connaissance de cause, notamment lorsqu'il procède par lui-même à leur saisie. Il est alors précisé à l'utilisateur du site www.GG.fr l’obligation ou non de fournir ces informations.<br>Conformément aux dispositions des articles 38 et suivants de la loi 78-17 du 6 janvier 1978 relative à l’informatique, aux fichiers et aux libertés, tout utilisateur dispose d’un droit d’accès, de rectification, de suppression et d’opposition aux données personnelles le concernant. Pour l’exercer, adressez votre demande à www.GG.fr par email : ou&nbsp;par écrit&nbsp;dûment signée, accompagnée d’une copie du titre d’identité avec signature du titulaire de la pièce, en précisant l’adresse à laquelle la réponse doit être envoyée.</p>
    <p class="text-justify">Aucune information personnelle de l'utilisateur du site www.GG.fr n'est publiée à l'insu de l'utilisateur, échangée, transférée, cédée ou vendue sur un support quelconque à des tiers. Seule l'hypothèse du rachat du site www.GG.fr et de ses droits autorise Erickson Sonny à transmettre les dites informations à l'éventuel acquéreur qui serait à son tour tenu&nbsp;à la même obligation de conservation et de modification des données vis à vis de l'utilisateur du site www.GG.fr.<br>Le site www.GG.fr est en conformité avec le RGPD voir notre politique RGPD&nbsp; jbb,nnlk.</p>
    <p class="text-justify">Les bases de données sont protégées par les dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données.</p>
  </div> 
<?php $content = ob_get_clean() ?>
<?php require 'view/template.php' ?>